<header>
    <nav>
        <h1><a href="/index.php">Ec0m</a></h1>
        <ul>
            <li><a href="/index.php">Accueil</a></li>
            <?php if (isAuthenticated()): ?>
                <li><a href="/product.php">Gestion des produits</a></li>
                <li><a href="/logout.php">Se déconnecter</a></li>
            <?php else: ?>
                <li><a href="/login.php">Se connecter</a></li>
            <?php endif; ?>
        </ul>
    </nav>
</header>