<body>
    <h1>Bienvenu sur Ec0m !</h1>
    <h2>Regardez nos produits :</h2>
    <div class="list-item">
        <?php

        foreach ($data as $product) {
            $title = $product['title'];
            $description = $product['description'];
            $price = $product['price'];
            $image_path = $product['image_path'];
            require("template/product.phtml");
        }
        ?>
    </div>
</body>