<div class="container-border">

    <h1>S'inscrire</h1>
    <hr>
    <section>
        <form action="/login.php" method="post">
            <input type="email" name="email" id="email" placeholder="example@mail.com">
            <input type="text" name="username" id="username" placeholder="pseudonyme">
            <input type="password" name="password" id="password">
            <input type="password" name="confirmPassword" id="confirmPassword">
            <input type="submit" value="S'inscrire">
        </form>
        <p>
            Tu as déjà un compte ? <a href="login.php">Cliquez ici !</a>
        </p>
    </section>

</div>