<div class="container-border">
    <h1>Ajouter un produit</h1>
    <hr>
    <form action="/add_product.php" method="POST" enctype="multipart/form-data" class="ecom_form">
        <label for="title">Titre</label>
        <input type="text" id="title" name="title" required>

        <label for="description">Description</label><br>
        <textarea id="description" name="description" required></textarea>

        <label for="price">Prix</label>
        <input type="number" id="price" name="price" step="0.01" required>

        <label for="image">Image du produit</label>
        <input type="file" id="image" name="image" accept="image/*" required>

        <button type="submit">Ajouter un produit</button>

    </form>
</div>