<div class="container-border">
    <h1>Add Product</h1>
    <form method="POST" enctype="multipart/form-data" class="form">
        <div class="mb-3">
            <label for="title">Titre</label>
            <input type="text" id="title" name="title" required>
        </div>

        <div class="mb-3">
            <label for="description">Description</label>
            <textarea id="description" name="description" rows="4" required></textarea>
        </div>

        <div class="mb-3">
            <label for="price">Prix</label>
            <input type="number" id="price" name="price" step="0.01" required>
        </div>

        <div class="mb-3">
            <label for="image">Image du produit</label>
            <input type="file" id="image" name="image" accept="image/*" required>
        </div>

        <button type="submit">Ajouter un produit</button>
    </form>
</div>