<div class="container-border">
    <h1>Modifier un produit</h1>
    <hr>
    <form action="/edit_product.php?id=<?= $id ?>" method="POST" enctype="multipart/form-data" class="ecom_form">
        <label for="title">Titre</label>
        <input type="text" id="title" name="title" required value="<?= $product['title'] ?>">

        <label for="description">Description</label><br>
        <textarea id="description" name="description" required><?= $product['description'] ?></textarea>

        <label for="price">Prix</label>
        <input type="number" id="price" name="price" step="0.01" required value="<?= $product['price'] ?>">

        <label for="image">Image du produit</label>
        <input type="file" id="image" name="image" accept="image/*">

        <?php if (!empty($product['image_path'])): ?>
            <p>Image actuelle :</p>
            <img src="<?= $product['image_path'] ?>" alt="Image du produit" style="max-width: 200px;">
        <?php endif; ?>

        <button type="submit">Modifier le produit</button>

    </form>
</div>