<div class="container-border">

    <h1>Se connecter</h1>
    <hr>
    <section>
        <form action="/login.php" method="post" id="loginForm">
            <input type="email" name="email" id="email" placeholder="example@mail.com">
            <input type="password" name="password" id="password">
            <input type="submit" value="Se connecter">
        </form>
        <p>
            Pas de compte ? <a href="register.php">Cliquez ici !</a>
        </p>
    </section>

</div>